#!/bin/bash
############# <MATE stuff> ############# 

export CARIDEN_ROOT=/opt/cariden
export CARIDEN_HOME=${CARIDEN_ROOT}/software/mate/current

PATH=$PATH:${CARIDEN_ROOT}/bin
PATH=$PATH:${CARIDEN_HOME}/bin

# Discovering MATE Live params
function mate_path {
        for path in "$CARIDEN_ROOT" "$HOME/.cariden/" "$CARIDEN_HOME" ;
        do
                [ -f $path/$1 ] && { echo "$path/$1"; break; }
        done
}

function mlconf_value {
	echo `cat $MLCONF | grep $1= | cut -f2 -d'='`
}

MLCONF=`mate_path etc/matelive/ml.conf`
MLData=`mlconf_value MLData`
MLDB=`mlconf_value Datastore`
[[ $MLDB ]] || MLDB=$MLData/datastore

export MLDATA
export MLDB
export MLCONF

alias mate='cd $CARIDEN_HOME'
alias l='cd $CARIDEN_HOME/lib/web/apache-tomcat-6.0.35/logs/'
alias logs='tail -f $CARIDEN_HOME/lib/web/apache-tomcat-6.0.35/logs/*log' 
alias webapps='cd $CARIDEN_HOME/lib/web/apache-tomcat-6.0.35/webapps/'
alias mls='ml status'
alias c='cd `dirname $MLCONF`'

############# </MATE stuff> ############# 
