#!/bin/bash

#############################################################################
## Author:       Jonathan Garzon
## Description:  Gather ML debug info
##
## History:
## - 0.1 JG 04/18/2013: Initial version (MATE 5.3.3)
## - 0.2 JG 04/18/2013: Added mld debug
##
#############################################################################

#############################################################################
# CHECK IF THIS IS VALID
#############################################################################

CONF_DIR=`license_check 2>&1 | grep lic | sed -e 's/.*: \(.*\/etc\)\(.*\).lic/\1/'`
CARIDEN_ROOT=`which license_check | sed 's/\(.*\)\/software\/mate\/current\/bin\/license_check/\1/'`

#############################################################################

MLCONF=$CONF_DIR/matelive/ml.conf
MLDATA=`cat $MLCONF | grep -v '^#' | grep MLData= | sed s,MLData=,,`
MLDB=`cat $MLCONF | grep -v '^#' | grep Datastore= | cut -f2 -d'='`
if [[ ! $MLDB ]]; then
	MLDB=$MLDATA/datastore
fi

echo "---------- Discovered Parameters ----------"
printf "%-15s = %s\n" "CARIDEN_ROOT" $CARIDEN_ROOT
printf "%-15s = %s\n" "CONFIG_DIR" $CONF_DIR
printf "%-15s = %s\n" "MLDATA" $MLDATA
printf "%-15s = %s\n" "MLDB" $MLDB
echo "-------------------------------------------"

if [[ ! $CARIDEN_ROOT ]] || [[ ! $CONF_DIR ]] || [[ ! $MLDATA ]]; then
	echo Invalid environment!
	exit 1
fi


if [[ "$1" != "tar" ]] && [[ "$1" != "print" ]]; then
	echo Usage: 
	echo "   ml_debug print : print some debug info"
	echo "   ml_debug tar   : create debug tarball"
	exit
fi

# DEBUG COMMANDS

IFS=$'\n'

COMMANDS_WITH_COMMENTS="
### MATE ###
$CARIDEN_ROOT/software/mate/current/bin/license_check -version
echo MLDATA=$MLDATA
echo MLDB=$MLDB
$CARIDEN_ROOT/software/mate/current/bin/license_check 

### System ###
uname -a
/bin/df -h
cat /proc/cpuinfo
cat /proc/meminfo
sar
top -n1 -b
ps aux
lsof -i -P
cat /etc/fstab
whoami
crontab -l
date
uptime

### MLD ###
# Datastore size
du -h $MLDB/*; echo; du -sh $MLDB
# Creation/update times
ml_read -datastore $MLDB sql \"select datetime(MIN(CreationTimestamp)/1000,'unixepoch','UTC') as FirstCreation, datetime(MAX(CreationTimestamp)/1000,'unixepoch','UTC') as LastCreation, datetime(MAX(UpdateTimestamp)/1000,'unixepoch','UTC') as LastUpdate from Interfaces LIMIT 5\"
# Tables size
for table in \`ml_read -datastore $MLDB tables\`; do c=\`ml_read -datastore $MLDB sql \"select count(*) from \$table;\" | tail -n1\`; printf \"%-30s%10d\\n\" \$table \$c; done
# Time to load the interfaces table with last value of time series
time ml_read sql 'select * from Interfaces_Series' 2>&1 | head

#### Logs ###
cat /opt/cariden/.cariden/etc/matelive/ml.conf | grep -v '^#' | grep -v ^$
tail -n1000 $CARIDEN_ROOT/software/mate/current/lib/web/apache-tomcat-6.0.35/logs/*
tail -n1000 $MLDB/mld.log
"

COMMANDS="`echo "$COMMANDS_WITH_COMMENTS" | grep -v '^#' | grep -v ^$`"
#echo "$COMMANDS";exit
i=1

# Create TMPDIR
DATE=`date --utc +%Y%m%d-%H%M` 
HOSTNAME=`hostname`
TMPDIR=`mktemp -d /tmp/ml_debug-$HOSTNAME-$DATE-XXX` 

touch $TMPDIR/debug
# Display commands to be executed

echo '*****************************************************' >> $TMPDIR/debug 2>&1
echo '* Commands in this output:                          *' >> $TMPDIR/debug 2>&1
echo '*****************************************************' >> $TMPDIR/debug 2>&1
for command in $COMMANDS; do
	echo CMD$i: $command >> $TMPDIR/debug 2>&1
	i=$((i+1))
done
echo '*****************************************************' >> $TMPDIR/debug 2>&1

# Execute commands

i=1
for command in $COMMANDS; do
	echo ----------------------------------------------------- >> $TMPDIR/debug 2>&1
	echo CMD$i: $command >> $TMPDIR/debug 2>&1
	echo ----------------------------------------------------- >> $TMPDIR/debug 2>&1
	bash -c $command >> $TMPDIR/debug 2>&1
	echo >> $TMPDIR/debug 2>&1
	echo >> $TMPDIR/debug 2>&1
	i=$((i+1))
done
if [ "$1" != "tar" ]; then
	cat $TMPDIR/debug
fi

NUMBER_OF_LOG_LINES=10000

if [ "$1" = "tar" ]; then 
	cp $MLDB/mldb $TMPDIR
	tail -$NUMBER_OF_LOG_LINES $MLDB/mld.log > $TMPDIR/last-10k-lines-mldb.log
	mkdir -p $TMPDIR/tomcat/logs
#	cp $CARIDEN_ROOT/software/mate/current/lib/web/apache-tomcat-6.0.35/logs/* $TMPDIR/tomcat/logs
	for file in `ls $CARIDEN_ROOT/software/mate/current/lib/web/apache-tomcat-6.0.35/logs/*`; do
		tail -$NUMBER_OF_LOG_LINES $file > $TMPDIR/tomcat/logs/last-10k-lines-`basename $file`
	done
	mkdir -p $TMPDIR/tomcat/conf
	cp -r $CARIDEN_ROOT/software/mate/current/lib/web/apache-tomcat-6.0.35/conf/* $TMPDIR/tomcat/conf

	echo -n "Creating $TMPDIR.tgz... "
	tar cvzf $TMPDIR.tgz -C /tmp/ `basename $TMPDIR` >/dev/null 2>&1
	if [[ $? == 0 ]]; then
		echo Done!
		ls -sh $TMPDIR.tgz
	else
		echo Error!
	fi
fi
rm -rf $TMPDIR
